---
title: "Aggression-Additional Analysis"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Additional Analysis W/ Selected Data, Significant Attributes
```{r}
library('caret')
df <- read.csv('cleandata.csv')
odf<- df[(df$aggressive_sumscore  <= (-2.020650971)) | (df$aggressive_sumscore  >= (0.2168869)), ]
odf$y <- ifelse(odf$aggressive_sumscore <= (-2.020650971), 0, 1)
df <- subset(odf, select=c(y, asr_scr_perstr_t, asr_scr_anxdep_t, asr_scr_aggressive_t, asr_scr_rulebreak_t, asr_scr_external_t, asr_scr_totprob_t, kbi_p_conflict, kbi_p_c_bully, kbi_p_c_mh_sa, fes_youth, fes_p_ss_fc_pr, macv_p_ss_r, demo_prnt_age_v2, demo_prnt_marital_v2, demo_comb_income_v2, demo_fam_exp, demo_yrs_2, neighborhood_crime_y, sex))
```

###Logistic Regression
Model Selection
```{r}
glm.fit <- glm(y ~ ., data = df, family = binomial)
```
Result
```{r}
summary(glm.fit)

cm <- confusionMatrix(table(as.numeric(glm.fit$fitted.values>0.5), df$y))
print(cm)
print(cm$byClass)
```

## Setup
Enviroment Setup
```{r, warning=FALSE}
bdf <- read.csv('./brain_cb.csv')
bdf <- bdf[complete.cases(bdf), ]        
bdf<- bdf[(bdf$aggressive_sumscore  <= (-2.02065)) | (bdf$aggressive_sumscore  >= (0.2168869)), ]
bdf$y <- ifelse(bdf$aggressive_sumscore <= (-2.02065), 0, 1)
```


## Analysis W/ Selected Data, Significant Attributes
Attribute selection
```{r}
df <- subset(bdf, select=c(y, rsfmri_cor_ngd_cerc_scs_thp, rsfmri_cor_ngd_cerc_scs_ag, rsfmri_cor_ngd_dsa_scs_thp, rsfmri_cor_ngd_dsa_scs_bs, rsfmri_cor_ngd_vta_scs_ag))
```

### Logistic Regression
Model Selection
```{r}
reg <- glm(y ~ ., data = df, family = binomial)
```
Result
```{r}
summary(reg)
cm <- confusionMatrix(table(as.numeric(reg$fitted.values>0.5), df$y))
print(cm)
print(cm$byClass)
```


### All Model 
```{r}
cdf <- read.csv('cleandata.csv')
bdf <- read.csv('brain_cb.csv')
df <- merge(x = cdf, y = bdf, by = "subjectkey", all.x = TRUE)

df <- df[complete.cases(df), ]        

df<- df[(df$aggressive_sumscore.x  <= (-2.020650971)) | (df$aggressive_sumscore.x  >= (0.2168869)), ]
df$y <- ifelse(df$aggressive_sumscore.x <= (-2.020650971), 0, 1)
```

```{r}
df <- subset(df, select=-c(X, prosocial_parent.x, prosocial_child.x,interview_date,  subjectkey, aggressive_sumscore.x, interview_age, aggressive_sumscore.y, prosocial_child.y, prosocial_parent.y))

reg <- glm(y ~ ., data = df, family = binomial)
summary(reg)
cm <- confusionMatrix(table(as.numeric(reg$fitted.values>0.5), df$y))
print(cm)
print(cm$byClass)
```
