---
title: "Analysis-Brain-AllData"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup
Enviroment Setup
```{r, warning=FALSE, results='hide'}
#setwd('~/Desktop/andlab/code')
odf <- read.csv('./brain_cb.csv')
odf <- odf[complete.cases(odf), ]        

library('caret')
#setwd('~/Desktop/andlab/code')
```
Function Define
```{r}
process <- function(df, reg, upr, plot=FALSE){
  
  newdf <- data.frame('y' = df$aggressive_sumscore)
  newdf$fitted <- reg$fitted.values
  
  newdf$class <- ifelse(newdf$y <= (-2.02065), 'L', ifelse(newdf$y>(upr),'M','H'))
  #change == -2.020650971 to change <= -2.020650971 to solve prediction for 0 is 0
  newdf$pred_class <-ifelse(newdf$fitted <= (-2.02065), 'L', ifelse(newdf$fitted>(upr),'M','H'))
  
  print(mean(newdf$pred_class == newdf$class))
  #cm <- confusionMatrix(factor(newdf$pred_class, levels = 0:2), factor(newdf$class, levels = 0:2) )
  cm <- confusionMatrix(table(newdf$class,newdf$pred_class))
  if(plot)
  {
    par(mfrow = c(2, 2))
    plot(reg)
  }
  return(cm=cm)
}

process_2_level <- function(df, reg, plot=FALSE){
  
  newdf <- data.frame('y' = df$aggressive_sumscore)
  newdf$fitted <- reg$fitted.values
  
  newdf$class <- ifelse(newdf$y <= (-2.020650971), 'L', 'H')
  #change == -2.020650971 to change <= -2.020650971 to solve prediction for 0 is 0
  newdf$pred_class <-ifelse(newdf$fitted <= (-2.020650971), 'L', 'H')
  
  print(mean(newdf$pred_class == newdf$class))
  #cm <- confusionMatrix(factor(newdf$pred_class, levels = 0:2), factor(newdf$class, levels = 0:2) )
  cm <- confusionMatrix(table(newdf$class,newdf$pred_class))
  if(plot)
  {
    par(mfrow = c(2, 2))
    plot(reg)
  }
  return(cm=cm)
}
```

## Analysis W/ All Data, All Attributes
Attribute selection
```{r}
df <- subset(odf, select=-c(prosocial_child, prosocial_parent, subjectkey))
```

### OLS
Model Selection
```{r}
reg <- lm(df$aggressive_sumscore ~ ., data=df)
```
Result
```{r}
summary(reg)
cm <- process(df, reg, -0.73254990)
print(cm)
print(cm$byClass)
```


### OLS W/ Interaction
Model Selection
```{r}
reg <- lm(df$aggressive_sumscore ~ . + .^2, data=df)
```
Result
```{r}
#summary(reg)
cm <- process(df, reg, -0.73254990)
print(cm)
print(cm$byClass)
```

### Stepwise
Model Selection
```{r}
null <- lm(aggressive_sumscore ~ 1, data=df)
full <- lm(aggressive_sumscore ~ ., data=df)
reg <- step(null, scope=formula(full), direction="forward", k=log(nrow(df)), trace=0)
```
Result
```{r}
summary(reg)
cm <- process(df, reg, -0.73254990)
print(cm)
print(cm$byClass)
```

### Stepwise W/ Interaction
Model Selection
```{r}
null <- lm(aggressive_sumscore ~ 1, data=df)
full <- lm(aggressive_sumscore ~ . + .^2, data=df)
reg <- step(null, scope=formula(full), direction="forward", k=log(nrow(df)), trace=0)
```
Result
```{r}
summary(reg)
cm <- process(df, reg, -0.73254990)
print(cm)
print(cm$byClass)
```

